import type { Metadata } from "next";
import { Provider } from "./queryClient";

export const metadata: Metadata = {
  title: "Hono | nextjs",
  description: "Generated by hono",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
